spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
      host: ${EMAIL_HOST_NAME}
      port: 25
      username: ${EMAIL_USER_NAME}
      password: ${EMAIL_PASSWORD}
      properties:
        mail:
          smtp:
            ssl:
              trust: "*"
            auth: true
            starttls:
              enable: true
            timeout: 10000
---
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  cors:
    # Add server address with port 8080 for backend and 8088 for frontend
    origins: http://localhost:4200,http://localhost:8080,http://localhost:8088
  file:
    uploads:
      photos-output-path: ./uploads
server:
  port: 8088
